services:
  tournament-manager-app:
    image: naderzare/foxsy-tournament-manager-app:latest
    container_name: foxsy-tournament-manager-app
    privileged: true
    environment:
      - DATA_DIR=${TOURNAMENT_MANAGER_DATA_DIR}
      - LOG_DIR=${TOURNAMENT_MANAGER_LOG_DIR}
      - DB=${TOURNAMENT_MANAGER_DB}
      - API_KEY=${TOURNAMENT_MANAGER_API_KEY}
      - FAST_API_PORT=${TOURNAMENT_MANAGER_FAST_API_PORT}
      - RABBITMQ_HOST=${TOURNAMENT_MANAGER_RABBITMQ_HOST}
      - RABBITMQ_PORT=${TOURNAMENT_MANAGER_RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${TOURNAMENT_MANAGER_RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${TOURNAMENT_MANAGER_RABBITMQ_PASSWORD}
      - TO_RUNNER_QUEUE=${TOURNAMENT_MANAGER_TO_RUNNER_QUEUE}
    networks:
      - dev_network
    ports:
      - "8085:8085"
    volumes:
      - ../data/tmanager:/app/data

networks:
  dev_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16