services:
 
  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      dev_network:
        ipv4_address: 10.200.0.4
    environment:
      MINIO_ROOT_USER: guest
      MINIO_ROOT_PASSWORD: guest1234
    command: server /data --console-address ":9001"
    volumes:
      - D:\workspace\foxsy\minio\minio-data:/data

networks:
  dev_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.0.0/16