version: '3.8'

services:
  runner-app:
    image: fox-run:latest
    container_name: foxsy-runner-app
    privileged: true
    environment:
      DATA_DIR: /home/appuser/app/data
      LOG_DIR: /home/appuser/app/data/logs
      API_KEY: api-key
      MAX_GAMES_COUNT: 5
      USE_FAST_API: "true"
      FAST_API_PORT: 8082
      USE_RABBITMQ: "true"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest1234
      TO_RUNNER_QUEUE: to-runner
      CONNECT_TO_TOURNAMENT_MANAGER: "false"
      TOURNAMENT_MANAGER_IP: localhost
      TOURNAMENT_MANAGER_PORT: 8085
      TOURNAMENT_MANAGER_API_KEY: api-key
      USE_MINIO: "true"
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: guest
      MINIO_SECRET_KEY: guest1234
      SERVER_BUCKET_NAME: server
      BASE_TEAM_BUCKET_NAME: baseteam
      TEAM_CONFIG_BUCKET_NAME: teamconfig
      GAME_LOG_BUCKET_NAME: gamelog
    networks:
      - dev_network
    ports:
      - "8082:8082"
    volumes:
      - ${RUNNER_APP_DATA_PATH}:/home/appuser/app/data


volumes:
  rabbitmq_data:

networks:
  dev_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16
