version: '3.8'

services:
  runner-app:
    image: naderzare/foxsy-runner-app:latest
    container_name: foxsy-runner-app
    privileged: true
    environment:
      DATA_DIR: /app/data
      LOG_DIR: /app/data/logs
      API_KEY: api-key
      MAX_GAMES_COUNT: 5
      USE_FAST_API: "true"
      FAST_API_PORT: 8082
      USE_RABBITMQ: "true"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      TO_RUNNER_QUEUE: to-runner
      TO_RUNNER_MANAGER_QUEUE: to-runner-manager-queue
      RUNNER_MANAGER_IP: localhost
      RUNNER_MANAGER_PORT: 5677
      RUNNER_MANAGER_API_KEY: runner-manager-api-key
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      SERVER_BUCKET_NAME: server
      BASE_TEAM_BUCKET_NAME: baseteam
      TEAM_CONFIG_BUCKET_NAME: teamconfig
      GAME_LOG_BUCKET_NAME: gamelog
    networks:
      - dev_network
    ports:
      - "8082:8082"
    volumes:
      - D:\workspace\foxsy\foxsy-tournament-runner\runner\data:/app/data


volumes:
  rabbitmq_data:

networks:
  dev_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16
