version: '3.8'

services:
  tournament-manager-app:
    image: naderzare/foxsy-tournament-manager-app:latest
    container_name: foxsy-tournament-manager-app
    privileged: true
    environment:
      DATA_DIR: /home/appuser/app/data
      LOG_DIR: /home/appuser/app/data/logs
      DB: example.db
      API_KEY: api-key
      FAST_API_PORT: 8085
      RABBITMQ_HOST: localhost
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest1234
      TO_RUNNER_QUEUE: to-runner
    networks:
      - dev_network
    ports:
      - "8085:8085"
    volumes:
      - ${RUNNER_APP_DATA_PATH}:/home/appuser/app/data


volumes:
  rabbitmq_data:

networks:
  dev_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.100.0.0/16
