services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Default RabbitMQ port
      - "15672:15672"  # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}  # Default username
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}  # Default password
    volumes:
      - ../data/rabbitmq:/var/lib/rabbitmq
    command: >
      sh -c "
      rabbitmq-plugins enable --offline rabbitmq_management &&
      rabbitmq-server
      "
